### PR TITLE
Add sourcemap feature for remote host debugging

### PR DESCRIPTION
**Pull request by felixfbecker**
@gianugo I switched from regexps to using url and path resolve and relative functions, which should be more robust. If you could confirm again that everything works I will merge this.

### CODE REVIEW

**Comment by AndrewNatoli** [comment]
Howdy
Looks like you were working with someone on this but in case it helps, I gave this a shot.... built the extension, plopped it into my copy of VSCode, and added the new parameters in the configurations object in launch.json. 

I made a few breakpoints in a file and started listening for connections but didn't have any luck debugging. I did check PHPStorm and Atom to make sure xdebug was set up properly and both were able to receive connections. 

Is there any other info I can provide that might be helpful?

**Comment by felixfbecker** [comment]
@AndrewNatoli Yes, it was a feature request of @gianugo. I personally don't need that feature and I don't have a remote server setup at hand, so I cannot test this - but without any remote settings or both set to the same local path everything works for me.

What did you test? Does it work without the settings or on the master branch? What kind of logs do you get in the debug console? What is XDebug logging when you set `xdebug.remote_log` to a log file in php.ini? Would you mind setting breakpoints in `convertDebuggerLineToClient` and the other to check if the paths are converted correctly?

**Comment by AndrewNatoli** [comment]
I'm using the `sourcemap` branch on OSX 10.11.1 and my server is Debian Squeeze.  I'm using PHP 5.3.29 with Xdebug 2.1.0.

Looks like it's communicating with xdebug and sends the breakpoints but they get rolled right over. 

```
<init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///var/www/project/file.php" language="PHP" protocol_version="1.0" appid="15973"><engine version="2.1.0"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2010 by Derick Rethans]]></copyright></init>

<- feature_set -i 0 -n max_depth -v 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="0" feature="max_depth" success="1"></response>

<- feature_set -i 1 -n max_children -v 9999
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="1" feature="max_children" success="1"></response>

<- breakpoint_set -i 2 -t line -f file:///Developer/project/file.php -n 8
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="2" id="159730001"></response>

<- run -i 3
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="3" status="stopping" reason="ok"></response>

<- stop -i 4
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="4" status="stopped" reason="ok"></response>
```

Developing and debugging works and the (truncated) response looks like:

```
<init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///Developer/project/file.php" language="PHP" protocol_version="1.0" appid="14210" idekey="andrew"><engine version="2.2.5"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2014 by Derick Rethans]]></copyright></init>

<- feature_set -i 0 -n max_depth -v 1
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="0" feature="max_depth" success="1"></response>

<- feature_set -i 1 -n max_children -v 9999
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="1" feature="max_children" success="1"></response>

<- breakpoint_set -i 2 -t line -f file:///Developer/project/file.php -n 8
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="2" id="142100001"></response>

<- run -i 3
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="3" status="break" reason="ok"><xdebug:message filename="file:///Developer/project/file.php" lineno="8"></xdebug:message></response>

<- stack_get -i 4
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="4"><stack where="{main}" level="0" type="file" filename="file:///Developer/project/file.php" lineno="8"></stack></response>

<- context_names -i 5 -d 0
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_names" transaction_id="5"><context name="Locals" id="0"></context><context name="Superglobals" id="1"></context></response>

<- context_get -i 6 -d 0 -c 0

...
```

How can I debug the actual extension? I've tried unsuccessfully so far... I tried "Debug Adapter" then set `--localSourceRoot` and `--serverSourceRoot` in the configuration. After running the sample index.php included it outputs "Accepted connection from client" then hangs without hitting any of the breakpoints I've set in the extension or PHP file. 

I also tried "launch extension," which popped open a new window... I opened my project, set its configuration, a breakpoint, and started listening to connections. Neither the extension debugger or actual extension caught anything.

**Comment by gianugo** [comment]
@felixfbecker sorry for disappearing on you - I'm on vacation and back to the office this coming Monday. This looks good and seems to work on my setup. @AndrewNatoli,  the instructions in the README for local debugging worked for me (with the caveat of #4). Can you try to add an xdebug_break() statement in your (remote) code and see if you get it to connect?

**Comment by felixfbecker** [comment]
@AndrewNatoli I have the feeling that your issue is not related to the sourcemaps feature, especially since your XDebug logs show breakpoint_set is sent correctly (and gets a successful response with a breakpoint ID). Do you have the same issue with the latest version from the VS Code marketplace? If yes, please open a separate issue so we can resolve this. Btw, `serverSourceRoot` should be set in launch.json, not as an argument like `--serverSourceRoot`.

In general, for debugging, there are two settings: One, you can _launch the extension_ without debugging it. An extension development host will open. In the testproject, the `debugServer` setting needs to be commented out for this, otherwise you will get an ECONNREFUSED. Second, you can _debug the adapter_. VS Code will listen for connections and you have to manually start the extension with `code testproject --extensionDevelopmentPath=/path/to/vscode-php-debug`. Then, inside the extension development host, uncomment `debugServer` and hit F5. If you see "connection accepted from client" it should work. If it doesn't, this must be some bug in VS Code.

@gianugo Is it save to merge?

**Comment by AndrewNatoli** [comment]
Thanks @gianugo, adding an `xdebug_break()` triggers a break that the debugger receives. All of my breakpoints in vscode are ignored however but that's a separate issue. 

@felixfbecker You're right about it not being a `sourcemaps` issue after all. Thanks for the help and explanations. The remote directory mapping is working for me as well, thanks!

**Comment by felixfbecker** [comment]
I will publish this after the VS Code January release and its changes and after implementing the conditional breakpoints.

**Pull request merged**
