### PR TITLE
fix: migrate enableBreakpointsFor in manifest

### PR DESCRIPTION
**Pull request by dsclee1**
Breakpoints declaration has moved in the package.json. This fixes it.

Fixes https://github.com/felixfbecker/vscode-php-debug/issues/424

### CODE REVIEW

**Comment by LLoyou00** [comment]
thank you

**Comment by mlabrum** [comment]
Any update on this?

**Comment by dsclee1** [comment]
The build fell over, but I think they've all fallen over for the past several months. Someone with write access will need to approve the commit.

**Comment by jonatanrs** [comment]
Today I have updated vscode to version **1.52.1** and the extension is **working again**

**Review by felixfbecker — APPROVED** [review]

**Pull request merged**
