### PR TITLE
Add hostname option to set the interface to bind to

### PR DESCRIPTION
**Pull request by martin-schulze-vireso**
This just amends mscharley's PR #289 by he changes that were requested over there.

### CODE REVIEW

**Comment by martin-schulze-vireso** [comment]
@felixfbecker The travis test seems to fail due to a missing dependency (`brew install php@7.0`) and not because of the new code.

**Comment by martin-schulze-vireso** [comment]
Seeing that you merged in master @felixfbecker, is there anything more I should do?

**Comment by felixfbecker** [comment]
Well the build is not passing and I'm not sure why

**Comment by martin-schulze-vireso** [comment]
@felixfbecker as mentioned above, installing php via brew fails (this is a problem of the CI not of the code). I am not well versed with brew so I cannot help much there but it [sounds like this version is not available anymore](https://www.reddit.com/r/PHP/comments/a4vggg/php_70_removed_from_homebrew/), so you probably need to do a php version bump on the recipe.

**Comment by martin-schulze-vireso** [comment]
@felixfbecker There I fixed it for you

**Comment by martin-schulze-vireso** [comment]
@felixfbecker Is there anything more needed?

**Pull request merged**
