### PR TITLE
Add ignore option to ignore paths

### LINKED ISSUE #33: Excluding folder paths from debugging
PHP version:  5.6 / 7.0
XDebug version:  2.4.0
Adapter version:  1.7.1

Your launch.json:  

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name"             : "PHP Web Application : XDebug",
            "type"             : "php",
            "request"          : "launch",
            "port"             : 9000,
            "serverSourceRoot" : "E:\\Development\\vps\\LeCoterie\\LeCoterie-Website"
        }
    ]
}
```

XDebug is working, however when verifying how XDebug works within vscode-php-debug versus PHPStorm I see a difference which causes issues with Laravel.

Basically, when I debug via PHPStorm, Laravel is using a plethora of Vendor items, of which some throw exceptions which are handled within the backend of PHPStorm (Testing for RegEx, etc) and doesn't cause any issues.

When I debug via VSCode, the exceptions are caught and by doing so actually stops the application from running as expected.

I am not sure how PHPStorm does it, but would there be any way of excluding paths from debugging, or adding in Exceptions types to be excluded from debugging.

### PR DESCRIPTION
**Pull request by felixfbecker**
Closes #33 
@VivPat @apit does this suit you?

### CODE REVIEW

**Comment by apit** [comment]
@felixfbecker yes. unfortunately i'm unable to debug `ignore` branch using latest Insiders :-(

**Comment by felixfbecker** [comment]
@apit why? Do the tests pass?

**Comment by xuanyou** [comment]
@apit I've gotten this branch to work and debug properly. The one error I've noticed:
- `"Unexpected token ..."` Check that your node version `node -v` is >= 5.x.x. Only Node 5+ supports the spread `...` operator.

@felixfbecker This branch works great on my setup.
- I'm running laravel and phpunit. The initial default ignore value `**/vendor/*.php` didn't exclude all subfolders, but once I changed it to `**/vendor/**/*.php` it worked. Same for phpunit, I added a `**/phpunit/**/*.php` and I could debug phpunit tests without error.
- The test results are the same as 1.10. All the tests pass except for those that need a debugging connection. I'm getting timeouts on my machine for those tests, but it's the same for both the "1.10" tag and "ignore" branch.

**Comment by QwertyZW** [comment]
Is this happening? https://github.com/felixfbecker/vscode-php-debug/tree/ignore

**Comment by felixfbecker** [comment]
Wanna write a test for it?

**Comment by felixfbecker** [comment]
@QwertyZW could you try out this branch and test if it works fine for your?

**Comment by QwertyZW** [comment]
It works as expected,

except that, like what @xuanyou mentioned, I had to use "**/vendor/**/*.php" instead of the default     "**/vendor/*.php"

**Comment by felixfbecker** [comment]
yeah, that makes sense. thanks for trying out

**Comment by noorcs** [comment]
Can someone please tell me where do i need to add this:

**/directoryToBeIgnored/**/*.php

???

**Comment by felixfbecker** [comment]
In launch.json

**Comment by noorcs** [comment]
I am unable to find launch.json

**Comment by felixfbecker** [comment]
Please read the vscode debugging documentation https://code.visualstudio.com/docs/editor/debugging

**Comment by noorcs** [comment]
@felixfbecker Thanks for the link. I checked on the link, but did not find anyway to add the ignore option to the launch.json. The way way it has been explained here "https://github.com/felixfbecker/vscode-php-debug/pull/66/commits/2b68a853c049a9a47186fee6880816747ecde1a5" does not work for me.

**Comment by felixfbecker** [comment]
@noorcs can you post your launch.json?

**Comment by noorcs** [comment]
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "ignore": [
                    "**/external/**/*.php",
                    "**/rtms/external/**/*.php"
                ]
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000,
            "ignore": [
                "**/external/**/*.php",
                "**/rtms/external/**/*.php"
            ]
        }
    ]
}`

**Comment by noorcs** [comment]
@felixfbecker  any ideas why isn't it working for me? I have tried it with many different settings, but no success yet. I am using latest updated version of vscode insiders.

**Comment by bilogic** [comment]
Does this 

1. ignore errors
2. or skip the file from debugging

I'm looking to skip, any ideas? Thank you.

**Comment by AnrDaemon** [comment]
I also look for ways to automatically step out of vendor code.

**Comment by AnrDaemon** [comment]
For the record, https://code.visualstudio.com/docs/editor/debugging does not mention any "ignore" functionality.

**Comment by bugproof** [comment]
I would prefer a whitelist that allows you to set paths you don't want to ignore.

**Pull request merged**
